name: anti_maling
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  # Paket untuk membaca sensor gerak
  sensors_plus: ^6.0.0 
  # Paket untuk memutar suara sirine
  audioplayers: ^6.5.0
  # (Opsional) Paket untuk getar
  vibration: ^3.1.3
  volume_controller: ^3.4.1
  flutter_volume_controller: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ 
